name: Create BookStack Page on New Issue

on:
  issues:
    types: [opened]

jobs:
  createPage:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install -g markdown-to-html-cli jq

      - name: Convert issue to BookStack page
        env:
          BOOKSTACK_API_ID: ${{ secrets.BOOKSTACK_API_ID }}
          BOOKSTACK_API_SECRET: ${{ secrets.BOOKSTACK_API_SECRET }}
          BOOKSTACK_URL: ${{ secrets.BOOKSTACK_URL }}
          BOOKSTACK_BOOK_ID: ${{ secrets.BOOKSTACK_BOOK_ID }}
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          ISSUE_URL="${{ github.event.issue.html_url }}"

          echo "$ISSUE_BODY" > issue.md
          markdown-to-html-cli issue.md -o issue.html
          HTML_BODY=$(cat issue.html | jq -Rs .)

          FULL_HTML="<p><strong>Связанная задача:</strong> <a href=\"$ISSUE_URL\">$ISSUE_URL</a></p>"
          FULL_HTML_ESCAPED=$(echo "$FULL_HTML" | jq -Rs .)

          echo "{
            \"name\": $ISSUE_TITLE | jq -Rs .,
            \"book_id\": \"$BOOKSTACK_BOOK_ID\",
            \"html\": ${FULL_HTML_ESCAPED%\"}$(echo ${HTML_BODY#\"})
          }" > payload.json

          curl -X POST "$BOOKSTACK_URL/api/pages" \
            -H "Authorization: Token $BOOKSTACK_API_ID:$BOOKSTACK_API_SECRET" \
            -H "Content-Type: application/json" \
            -d @payload.json
