name: Create BookStack Page on New Issue

on:
  issues:
    types: [opened]

jobs:
  createPage:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install -g markdown-to-html-cli jq

      - name: Convert issue to BookStack page
        env:
          BOOKSTACK_API_ID: ${{ secrets.BOOKSTACK_API_ID }}
          BOOKSTACK_API_SECRET: ${{ secrets.BOOKSTACK_API_SECRET }}
          BOOKSTACK_URL: ${{ secrets.BOOKSTACK_URL }}
          BOOKSTACK_BOOK_ID: ${{ secrets.BOOKSTACK_BOOK_ID }}
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          ISSUE_URL="${{ github.event.issue.html_url }}"

          echo "$ISSUE_BODY" > issue.md

          # Конвертация Markdown в HTML
          markdown-to-html-cli --input issue.md --output issue.html

          # Экранируем HTML и подготавливаем JSON
          HTML_BODY=$(cat issue.html | jq -Rs .)
          HEADER_HTML="<p><strong>Связанная задача:</strong> <a href=\"$ISSUE_URL\">$ISSUE_URL</a></p>"
          HEADER_ESCAPED=$(echo "$HEADER_HTML" | jq -Rs .)

          # Объединение HTML
          COMBINED_HTML=$(echo "${HEADER_ESCAPED%\"}$(echo ${HTML_BODY#\"})")

          # Запись payload
          echo "{
            \"name\": $(echo \"$ISSUE_TITLE\" | jq -Rs .),
            \"book_id\": \"$BOOKSTACK_BOOK_ID\",
            \"html\": $COMBINED_HTML
          }" > payload.json

          # Отправка запроса в BookStack
          curl -X POST "$BOOKSTACK_URL/api/pages" \
            -H "Authorization: Token $BOOKSTACK_API_ID:$BOOKSTACK_API_SECRET" \
            -H "Content-Type: application/json" \
            -d @payload.json
