name: Create BookStack Page on New Issue

on:
  issues:
    types: [opened]

jobs:
  createPage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (optional if needed)
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Markdown converter
        run: npm install -g markdown-to-html-cli

      - name: Convert Markdown to HTML and create BookStack page
        env:
          BOOKSTACK_API_ID: ${{ secrets.BOOKSTACK_API_ID }}
          BOOKSTACK_API_SECRET: ${{ secrets.BOOKSTACK_API_SECRET }}
          BOOKSTACK_URL: ${{ secrets.BOOKSTACK_URL }}
          BOOKSTACK_BOOK_ID: ${{ secrets.BOOKSTACK_BOOK_ID }}
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          ISSUE_URL="${{ github.event.issue.html_url }}"

          # Сохраняем тело задачи в .md файл
          echo "$ISSUE_BODY" > issue.md

          # Конвертируем markdown → html
          markdown-to-html-cli issue.md -o issue.html

          # Подготавливаем JSON-платеж для BookStack API
          HTML_BODY=$(cat issue.html | jq -Rs .)

          echo "{
            \"name\": \"$ISSUE_TITLE\",
            \"book_id\": \"$BOOKSTACK_BOOK_ID\",
            \"html\": \"<p><strong>Связанная задача:</strong> <a href='$ISSUE_URL'>$ISSUE_URL</a></p>\" + $HTML_BODY
          }" > payload.json

          # Отправляем запрос
          curl -X POST "$BOOKSTACK_URL/api/pages" \
            -H "Authorization: Token $BOOKSTACK_API_ID:$BOOKSTACK_API_SECRET" \
            -H "Content-Type: application/json" \
            -d @payload.json
